'use client'
import { FormEvent, useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { Navbar } from '@/components/navigation/Navbar'
import { Button } from '@/components/ui/Button'
import { Card } from '@/components/ui/Card'
import { apiFetch, rememberCsrfToken } from '@/lib/api'

const safeReturnTo = (value: string | null) => value?.startsWith('/invitations/accept?intent=') || value === '/dashboard' || value === '/onboarding' ? value : '/onboarding'
export default function LoginPage(){const router=useRouter();const[email,setEmail]=useState('');const[mode,setMode]=useState<'login'|'register'>('login');const[message,setMessage]=useState('');const[error,setError]=useState('');const[loading,setLoading]=useState(false);const params=typeof window==='undefined'?new URLSearchParams():new URLSearchParams(window.location.search);const returnTo=safeReturnTo(params.get('returnTo'));useEffect(()=>{const token=params.get('token');if(!token)return;apiFetch('/api/auth/magic-link/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token})}).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.detail||'Lenken kunne ikke brukes.');rememberCsrfToken(data.csrf_token);router.replace(returnTo)}).catch(e=>setError(e instanceof Error?e.message:'Lenken kunne ikke brukes.'))},[router,returnTo]);const submit=async(e:FormEvent)=>{e.preventDefault();setLoading(true);setError('');try{const r=await apiFetch(mode==='login'?'/api/auth/email/request':'/api/auth/register/email/request',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,return_to:returnTo})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.detail||'Kunne ikke sende e-post.');setMessage(data.message)}catch(x){setError(x instanceof Error?x.message:'Kunne ikke sende e-post.')}finally{setLoading(false)}};return <div className="min-h-screen bg-bonde-oat"><Navbar/><main className="flex justify-center p-6 py-16"><Card hoverEffect={false} className="w-full max-w-md bg-white p-8"><h1 className="text-3xl font-serif">{mode==='login'?'Logg inn':'Opprett konto'}</h1><div className="mt-4 flex gap-3"><button onClick={()=>setMode('login')}>Logg inn</button><button onClick={()=>setMode('register')}>Opprett konto</button></div>{error&&<p className="mt-4 text-red-700">{error}</p>}{message&&<p className="mt-4 text-bonde-green">{message}</p>}<form onSubmit={submit} className="mt-6 space-y-4"><input className="w-full rounded border p-3" required type="email" value={email} onChange={e=>setEmail(e.target.value)}/><Button type="submit" disabled={loading} variant="primary" fullWidth>{loading?'Sender…':'Fortsett'}</Button></form></Card></main></div>}
