'use client'
import { FormEvent, useEffect, useState } from 'react'
import { Navbar } from '@/components/navigation/Navbar'
import { apiErrorMessage, apiFetch, bootstrapIdentity } from '@/lib/api'

export default function FarmSettingsPage() {
  const [farmId, setFarmId] = useState(''); const [data, setData] = useState<Record<string, unknown> | null>(null); const [message, setMessage] = useState('')
  useEffect(() => { bootstrapIdentity().then(async identity => { const id = identity?.active_farm?.id || ''; setFarmId(id); if (!id) return; const r = await apiFetch(`/api/farms/${encodeURIComponent(id)}/settings`); if (!r.ok) return setMessage(await apiErrorMessage(r, 'Kunne ikke hente gårdsinnstillinger.')); setData(await r.json()) }).catch(() => setMessage('Du må logge inn.')) }, [])
  const save = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); if (!farmId) return; const body = Object.fromEntries(new FormData(e.currentTarget)); const r = await apiFetch(`/api/farms/${encodeURIComponent(farmId)}/settings`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); if (!r.ok) return setMessage(await apiErrorMessage(r, 'Kunne ikke lagre innstillingene.')); setData(await r.json()); setMessage('Gårdsinnstillingene er lagret.') }
  const value = (name: string) => String(data?.[name] || '')
  return <div className="min-h-screen bg-bonde-oat"><Navbar /><main className="mx-auto max-w-3xl p-6"><h1 className="text-3xl font-serif">Gårdsinnstillinger</h1><p className="mt-2 text-sm text-stone-600">Organisasjonsnummer og BRREG-opplysninger endres i gårdsoppsettet, ikke her.</p>{message && <p className="mt-4 text-sm">{message}</p>}{data && <form onSubmit={save} className="mt-6 grid gap-4 rounded-xl bg-white p-6 shadow-sm sm:grid-cols-2"><label>Gårdsnavn<input name="display_name" defaultValue={value('display_name')} className="mt-1 w-full rounded border p-2" /></label><label>Juridisk navn<input disabled value={value('legal_name')} className="mt-1 w-full rounded border p-2 text-stone-500" /></label><label>Adresse<input name="address_line_1" defaultValue={value('address_line_1')} className="mt-1 w-full rounded border p-2" /></label><label>Postnummer<input name="postal_code" defaultValue={value('postal_code')} className="mt-1 w-full rounded border p-2" /></label><label>Sted<input name="city" defaultValue={value('city')} className="mt-1 w-full rounded border p-2" /></label><label>Kontakt-e-post<input name="contact_email" defaultValue={value('contact_email')} className="mt-1 w-full rounded border p-2" /></label><label>Faktura-e-post<input name="invoice_email" defaultValue={value('invoice_email')} className="mt-1 w-full rounded border p-2" /></label><label>Betalingsfrist<input name="payment_terms_days" type="number" min="0" max="90" defaultValue={value('payment_terms_days')} className="mt-1 w-full rounded border p-2" /></label><label>MVA-status<select name="vat_registered" defaultValue={value('vat_registered')} className="mt-1 w-full rounded border p-2"><option value="unknown">Ukjent</option><option value="yes">Ja</option><option value="no">Nei</option></select></label><label>Regnskapsår starter<input name="accounting_year_start" defaultValue={value('accounting_year_start')} className="mt-1 w-full rounded border p-2" /></label><button className="rounded bg-bonde-green px-4 py-2 font-semibold text-white sm:col-span-2">Lagre innstillinger</button></form>}</main></div>
}
